In [182]:
pip install pandas

Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in .\anaconda3\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [183]:
import pandas as pd

In [184]:
pd.__version__

'2.3.3'

In [185]:
#1.Create dataframe
df=pd.DataFrame([1,2,3],columns=['Number'])
print(df)
print(type(df))

   Number
0       1
1       2
2       3
<class 'pandas.core.frame.DataFrame'>

In [186]:
data={
    'Name':['Nitin','Sagar','Sudip','Omkar'],
    'Age':[25,24,26,23],
    'Salary':[700000,80000,90000,50000]
}

In [187]:
df=pd.DataFrame(data)
df

    Name  Age  Salary
0  Nitin   25  700000
1  Sagar   24   80000
2  Sudip   26   90000
3  Omkar   23   50000

In [188]:
#2. Basic DataFrame understanding

In [189]:
df.head(10)
df.tail()
df.shape
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [190]:
df.rename(columns={'Salary': 'Monthly_Salary'},inplace=True)

In [191]:
df

    Name  Age  Monthly_Salary
0  Nitin   25          700000
1  Sagar   24           80000
2  Sudip   26           90000
3  Omkar   23           50000

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [193]:
df.describe()

             Age  Monthly_Salary
count   4.000000         4.00000
mean   24.500000    230000.00000
std     1.290994    313793.98762
min    23.000000     50000.00000
25%    23.750000     72500.00000
50%    24.500000     85000.00000
75%    25.250000    242500.00000
max    26.000000    700000.00000

In [194]:
df

    Name  Age  Monthly_Salary
0  Nitin   25          700000
1  Sagar   24           80000
2  Sudip   26           90000
3  Omkar   23           50000

In [195]:
df.to_csv('Test_data.csv',index=False)

In [196]:
import os
print(os.getcwd())

C:\Users\nitin

In [197]:
df_new= pd.read_csv(r"C:\Users\nitin\Test_data.csv")

In [198]:
df_new

    Name  Age  Monthly_Salary
0  Nitin   25          700000
1  Sagar   24           80000
2  Sudip   26           90000
3  Omkar   23           50000

In [199]:
#select column
#df[['NAME']] single column
df[['Name','Monthly_Salary']]

    Name  Monthly_Salary
0  Nitin          700000
1  Sagar           80000
2  Sudip           90000
3  Omkar           50000

In [200]:
#Select row
df.loc[df.Name=='Nitin']
df.loc[(df.Name=='Nitin') &(df.Monthly_Salary>=50000)]

    Name  Age  Monthly_Salary
0  Nitin   25          700000

In [201]:
df.iloc[0:2]

    Name  Age  Monthly_Salary
0  Nitin   25          700000
1  Sagar   24           80000

In [202]:
#Filter DataFrame

In [203]:
df

    Name  Age  Monthly_Salary
0  Nitin   25          700000
1  Sagar   24           80000
2  Sudip   26           90000
3  Omkar   23           50000

In [204]:
df[df['Age']>24]

    Name  Age  Monthly_Salary
0  Nitin   25          700000
2  Sudip   26           90000

In [205]:
df.where(df['Monthly_Salary']>50000, other='Not eligible')

           Name           Age Monthly_Salary
0         Nitin            25         700000
1         Sagar            24          80000
2         Sudip            26          90000
3  Not eligible  Not eligible   Not eligible

In [206]:
# How to add new row and column'
df

    Name  Age  Monthly_Salary
0  Nitin   25          700000
1  Sagar   24           80000
2  Sudip   26           90000
3  Omkar   23           50000

In [207]:
df['Team']=['Data_Analyst','System_Eng','DE','SDE']
df

    Name  Age  Monthly_Salary          Team
0  Nitin   25          700000  Data_Analyst
1  Sagar   24           80000    System_Eng
2  Sudip   26           90000            DE
3  Omkar   23           50000           SDE

In [208]:
#add new row
df.loc[len(df)]=['Vinayak',10,22000,'IT']
df

      Name  Age  Monthly_Salary          Team
0    Nitin   25          700000  Data_Analyst
1    Sagar   24           80000    System_Eng
2    Sudip   26           90000            DE
3    Omkar   23           50000           SDE
4  Vinayak   10           22000            IT

In [209]:
len(df)

5

In [210]:
#update value

df.loc[0,'Monthly_Salary']=950000
df

      Name  Age  Monthly_Salary          Team
0    Nitin   25          950000  Data_Analyst
1    Sagar   24           80000    System_Eng
2    Sudip   26           90000            DE
3    Omkar   23           50000           SDE
4  Vinayak   10           22000            IT

In [211]:
df.loc[df.Name=='Nitin','Monthly_Salary']=450000
df

      Name  Age  Monthly_Salary          Team
0    Nitin   25          450000  Data_Analyst
1    Sagar   24           80000    System_Eng
2    Sudip   26           90000            DE
3    Omkar   23           50000           SDE
4  Vinayak   10           22000            IT

In [212]:
#delete value

df=df.drop(df[df.Name=='Vinayak'].index)
df

    Name  Age  Monthly_Salary          Team
0  Nitin   25          450000  Data_Analyst
1  Sagar   24           80000    System_Eng
2  Sudip   26           90000            DE
3  Omkar   23           50000           SDE

In [213]:
df=df.rename(columns={'Monthly_Salary':'Salary'})

In [214]:
# Working Date and time datatype

In [215]:
df['DOJ']=['2024-01-13','2024-02-13','2024-03-13','2024-04-13']

In [216]:
df

    Name  Age  Salary          Team         DOJ
0  Nitin   25  450000  Data_Analyst  2024-01-13
1  Sagar   24   80000    System_Eng  2024-02-13
2  Sudip   26   90000            DE  2024-03-13
3  Omkar   23   50000           SDE  2024-04-13

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
 3   Team    4 non-null      object
 4   DOJ     4 non-null      object
dtypes: int64(2), object(3)
memory usage: 192.0+ bytes

In [218]:
df['DOJ'].dtype

dtype('O')

In [219]:
df1=df

In [220]:
df1['DOJ2']=['2025-02-11','2025-04-13','2025-03-15','2025-06-13']

In [221]:
df

    Name  Age  Salary          Team         DOJ        DOJ2
0  Nitin   25  450000  Data_Analyst  2024-01-13  2025-02-11
1  Sagar   24   80000    System_Eng  2024-02-13  2025-04-13
2  Sudip   26   90000            DE  2024-03-13  2025-03-15
3  Omkar   23   50000           SDE  2024-04-13  2025-06-13

In [222]:
df1

    Name  Age  Salary          Team         DOJ        DOJ2
0  Nitin   25  450000  Data_Analyst  2024-01-13  2025-02-11
1  Sagar   24   80000    System_Eng  2024-02-13  2025-04-13
2  Sudip   26   90000            DE  2024-03-13  2025-03-15
3  Omkar   23   50000           SDE  2024-04-13  2025-06-13

In [223]:
df=df.drop('DOJ2',axis=1)

In [224]:
df

    Name  Age  Salary          Team         DOJ
0  Nitin   25  450000  Data_Analyst  2024-01-13
1  Sagar   24   80000    System_Eng  2024-02-13
2  Sudip   26   90000            DE  2024-03-13
3  Omkar   23   50000           SDE  2024-04-13

In [225]:
df['DOJ']=pd.to_datetime(df['DOJ'])

In [226]:
df['DOJ'].dt.year

0    2024
1    2024
2    2024
3    2024
Name: DOJ, dtype: int32

In [227]:
df['DOJ'].dt.month

0    1
1    2
2    3
3    4
Name: DOJ, dtype: int32

In [228]:
df['DOJ'].dt.day

0    13
1    13
2    13
3    13
Name: DOJ, dtype: int32

In [229]:
df['DOJ'].dt.day_name()

0     Saturday
1      Tuesday
2    Wednesday
3     Saturday
Name: DOJ, dtype: object

In [230]:
df['Month']=df['DOJ'].dt.month

In [231]:
df

    Name  Age  Salary          Team        DOJ  Month
0  Nitin   25  450000  Data_Analyst 2024-01-13      1
1  Sagar   24   80000    System_Eng 2024-02-13      2
2  Sudip   26   90000            DE 2024-03-13      3
3  Omkar   23   50000           SDE 2024-04-13      4

In [232]:
# Handling missing value

df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [233]:
import numpy as np

In [234]:
df.loc[df.Name=='Nitin']= np.nan

In [235]:
df

    Name   Age   Salary        Team        DOJ  Month
0    NaN   NaN      NaN         NaN        NaT    NaN
1  Sagar  24.0  80000.0  System_Eng 2024-02-13    2.0
2  Sudip  26.0  90000.0          DE 2024-03-13    3.0
3  Omkar  23.0  50000.0         SDE 2024-04-13    4.0

In [236]:
df.isnull().sum()

Name      1
Age       1
Salary    1
Team      1
DOJ       1
Month     1
dtype: int64

In [237]:
df['Month'] = df['Month'].fillna(0).astype(int)

In [238]:
#Aggregation and group by

In [239]:
df['Month'].value_counts()

Month
0    1
2    1
3    1
4    1
Name: count, dtype: int64

In [240]:
df

    Name   Age   Salary        Team        DOJ  Month
0    NaN   NaN      NaN         NaN        NaT      0
1  Sagar  24.0  80000.0  System_Eng 2024-02-13      2
2  Sudip  26.0  90000.0          DE 2024-03-13      3
3  Omkar  23.0  50000.0         SDE 2024-04-13      4

In [241]:
df['Month'] = df['Month'].astype(int)

In [242]:
df

    Name   Age   Salary        Team        DOJ  Month
0    NaN   NaN      NaN         NaN        NaT      0
1  Sagar  24.0  80000.0  System_Eng 2024-02-13      2
2  Sudip  26.0  90000.0          DE 2024-03-13      3
3  Omkar  23.0  50000.0         SDE 2024-04-13      4

In [245]:
df[df['Month']==2].value_counts()

Name   Age   Salary   Team        DOJ         Month
Sagar  24.0  80000.0  System_Eng  2024-02-13  2        1
Name: count, dtype: int64

In [246]:
df.groupby('Month')['Salary'].sum()

Month
0        0.0
2    80000.0
3    90000.0
4    50000.0
Name: Salary, dtype: float64

In [247]:
#concatenate and merge dataframe

In [249]:
df1=pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})

In [250]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [252]:
df2=pd.DataFrame({'ID':[1,2,2,3],'Score':[22,66,66,55]})

In [253]:
df2

   ID  Score
0   1     22
1   2     66
2   2     66
3   3     55

In [254]:
pd.concat([df1,df2],axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   22.0
1   2  NaN   66.0
2   2  NaN   66.0
3   3  NaN   55.0

In [255]:
pd.concat([df1,df2],axis=1)

    ID Name  ID  Score
0  1.0    A   1     22
1  2.0    B   2     66
2  3.0    C   2     66
3  NaN  NaN   3     55

In [256]:
# Merge Join

In [257]:
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     22
1   2    B     66
2   2    B     66
3   3    C     55

In [5]:
import pandas as pd

In [6]:
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
#create a series from dictionary

data={'a':1,'b':2}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
dtype: int64

In [13]:
#createing a dataframe from a dictionary

data=[{'Name':'Nitin','Age':25},
      {'Name':'Omakr','Age':25},
{'Name':'Sai','Age':25}]
df=pd.DataFrame(data)
print(df)

    Name  Age
0  Nitin   25
1  Omakr   25
2    Sai   25

In [14]:
pd.read_csv('sales_data.csv' )

FileNotFoundError: [Errno 2] No such file or directory: 'sales_data.csv'